app = "signal-backend"
primary_region = "dfw"  # Dallas

[build]
  dockerfile = "Dockerfile"

[env]
  ALLOWED_ORIGINS = "https://signal.abruno.net"
  CHAT_HISTORY_LIMIT = "3"
  CHROMA_COLLECTION = "signal_knowledge"
  CHROMA_HOST = "signal-rag-chroma.internal"
  CHROMA_PORT = "8000"
  OPENROUTER_MODEL = "google/gemini-2.5-flash"
  OPENROUTER_TEMP = "0.8"
  LOG_LEVEL = "error"
  MCP_SERVER_URL = "https://signal-mcp.fly.dev"
  MCP_TRANSPORT = "http"
  NODE_ENV = "production"
  OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"
  PORT = "3000"
  RATE_LIMIT_MAX_REQUESTS = "20"
  RATE_LIMIT_WINDOW_MS = "60000"
  RETRIEVAL_MIDDLE_CUTOFF = "0.3"
  RETRIEVAL_MIDDLE_TOP_K = "10"
  RETRIEVAL_STRONG_CUTOFF = "0.2"
  RETRIEVAL_STRONG_TOP_K = "20"
  RETRIEVAL_WEAK_CUTOFF = "0.2"
  RETRIEVAL_WEAK_TOP_K = "25"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/health"
    protocol = "http"

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512